# Generated by Django 5.2.1 on 2025-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_alter_skill_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('LIN', 'Link'), ('HLD', 'Holding')], default='PEN', max_length=3),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogPostCategory',
        ),
    ]
